### PR TITLE
Textfield patch

### PR DESCRIPTION
**Pull request by julbar**

### CODE REVIEW

**Review by m-karczewska — APPROVED** [review]
Looks all good to me

**Comment by julbar** [comment]
@m-karczewska I have made some changes bigger changes now, if you could take a quick look again please :)

**Comment by m-karczewska** [comment]
> @m-karczewska I have made some changes bigger changes now, if you could take a quick look again please :)

All is fine :) not blocking the merge, just curious - why do you now use BasicTextField instead of OutlinedTextField? It looks good in the app, but I'm not sure I understand the reason

**Comment by julbar** [comment]
Using the BasicTextField because we need to left align the text in read-only mode and also because we want the text to not be red when typing in error mode.

**Pull request merged**
